-- Run this once in Supabase: SQL Editor > New query > Run.
create extension if not exists pgcrypto;
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, username text not null check (char_length(username) between 2 and 32), role text not null default 'member' check (role in ('member','admin')), created_at timestamptz not null default now());
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,username,role) values(new.id,coalesce(nullif(new.raw_user_meta_data->>'username',''),split_part(new.email,'@',1)),case when new.email='3538882915@qq.com' then 'admin' else 'member' end); return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users; create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
insert into public.profiles(id,username,role) select id,coalesce(nullif(raw_user_meta_data->>'username',''),split_part(email,'@',1)),case when email='3538882915@qq.com' then 'admin' else 'member' end from auth.users on conflict(id) do update set role=excluded.role;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='admin'); $$;
create table if not exists public.posts (id uuid primary key default gen_random_uuid(), author_id uuid not null references public.profiles(id) on delete cascade, body text not null check(char_length(body) between 1 and 5000), official boolean not null default false, created_at timestamptz not null default now());
create table if not exists public.post_media (id uuid primary key default gen_random_uuid(), post_id uuid not null references public.posts(id) on delete cascade, path text not null unique, mime_type text not null, created_at timestamptz not null default now());
alter table public.profiles enable row level security; alter table public.posts enable row level security; alter table public.post_media enable row level security;
create policy "profiles visible" on public.profiles for select using(true); create policy "profile own update" on public.profiles for update using(id=auth.uid()) with check(id=auth.uid() and role=(select role from public.profiles where id=auth.uid()));
create policy "posts visible" on public.posts for select using(true); create policy "post own or admin insert" on public.posts for insert to authenticated with check(author_id=auth.uid() and (not official or public.is_admin())); create policy "post delete" on public.posts for delete to authenticated using(author_id=auth.uid() or public.is_admin()); create policy "post update" on public.posts for update to authenticated using(author_id=auth.uid() or public.is_admin()) with check(author_id=auth.uid() or public.is_admin());
create policy "media visible" on public.post_media for select using(true); create policy "media author insert" on public.post_media for insert to authenticated with check(exists(select 1 from public.posts where id=post_id and author_id=auth.uid())); create policy "media delete" on public.post_media for delete to authenticated using(exists(select 1 from public.posts where id=post_id and (author_id=auth.uid() or public.is_admin())));
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('forum-media','forum-media',true,20971520,array['image/jpeg','image/png','image/webp','image/gif','audio/mpeg','audio/ogg','audio/wav','audio/mp4']) on conflict(id) do nothing;
create policy "media upload own folder" on storage.objects for insert to authenticated with check(bucket_id='forum-media' and (storage.foldername(name))[1]=auth.uid()::text); create policy "media public read" on storage.objects for select using(bucket_id='forum-media'); create policy "media delete own or admin" on storage.objects for delete to authenticated using(bucket_id='forum-media' and ((storage.foldername(name))[1]=auth.uid()::text or public.is_admin()));
