(() => {
  const db = window.forumAuth; if (!db) return;
  let user, level = 0, canModerate = false, files = [], posts = [], filter = '全部';
  const form = document.querySelector('[data-post-form]'), list = document.querySelector('[data-post-list]'), note = document.querySelector('[data-forum-note]'), search = document.querySelector('[data-post-search]');
  const esc = v => String(v || '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const render = () => {
    const q = search.value.trim().toLowerCase();
    const shown = posts.filter(p => (filter === '全部' || p.category === filter) && `${p.body} ${p.author_name} ${p.category}`.toLowerCase().includes(q)).sort((a,b) => Number(b.is_pinned) - Number(a.is_pinned) || new Date(b.created_at) - new Date(a.created_at));
    list.innerHTML = shown.length ? shown.map(p => {
      const reactions = p.post_reactions || [], count = kind => reactions.filter(r => r.kind === kind).length;
      const media = (p.post_media || []).map(m => m.mime_type.startsWith('image/') ? `<img src="${db.storage.from('forum-media').getPublicUrl(m.path).data.publicUrl}">` : `<audio controls src="${db.storage.from('forum-media').getPublicUrl(m.path).data.publicUrl}"></audio>`).join('');
      const verified=p.profiles?.is_verified?` <span class="official">${esc(p.profiles.verification_label||'论坛认证')} ✓</span>`:'';
      return `<article class="post"><div class="post-top"><div><div class="post-author">${p.official ? '<span class="official">论坛站内官方认证 ✓</span> ' : ''}${esc(p.author_name)}${verified} ${p.is_pinned ? '<span class="wiki-tag">置顶</span>' : ''}</div><div class="post-meta"><span class="wiki-tag">${esc(p.category || '综合交流')}</span> ${p.show_timestamp ? new Date(p.created_at).toLocaleString('zh-CN') : ''}</div></div>${user && (user.id === p.author_id || canModerate) ? `<button class="delete-post" data-delete="${p.id}">删除</button>` : ''}</div><div class="post-body">${esc(p.body)}</div><div class="post-media">${media}</div><div class="post-actions"><button data-react="like" data-id="${p.id}">点赞 ${count('like')}</button><button data-react="favorite" data-id="${p.id}">收藏 ${count('favorite')}</button><button data-react="share" data-id="${p.id}">转发 ${count('share')}</button>${(!p.official || p.comment_enabled) ? `<a href="post.html?id=${p.id}">评论 / 讨论</a>` : ''}<button data-report="${p.id}">举报</button></div></article>`;
    }).join('') : '<p class="forum-note">没有符合条件的内容。</p>';
  };
  async function load(){ const [{data,error},{data:cards=[]}]=await Promise.all([db.from('posts').select('*,post_media(*),post_reactions(kind,user_id)').order('created_at',{ascending:false}),db.from('public_profile_cards').select('id,is_verified,verification_label')]); if(error) list.textContent=`加载失败：${error.message}`; else {const by=Object.fromEntries(cards.map(x=>[x.id,x]));posts=(data||[]).map(x=>({...x,profiles:by[x.author_id]}));render();} }
  async function init(){ ({data:{user}} = await db.auth.getUser()); if(!user) return; const {data:p}=await db.from('profiles').select('role,level').eq('id',user.id).single(); level=p?.level||0; canModerate=['admin','superadmin'].includes(p?.role); document.querySelector('[data-official-wrap]').hidden=!canModerate; note.textContent=canModerate?'管理模式：可发布官方公告。':level===0?'LV0：仅可浏览社区内容。':level<5?'LV1–4：最多 5 帖、每帖不超过 30 字，暂不能上传媒体。':'可以发布内容和媒体。'; if(level<1&&!canModerate) form.querySelector('[type=submit]').disabled=true; document.querySelector('[data-media-wrap]').hidden=level<5&&!canModerate; await load(); }
  form.querySelector('[name=official]').addEventListener('change',e=>document.querySelector('[data-official-options]').hidden=!e.target.checked);
  form.querySelector('input[type=file]').addEventListener('change',e=>{files=[...e.target.files]; document.querySelector('[data-file-list]').textContent=files.map(f=>f.name).join('、');});
  form.addEventListener('submit',async e=>{e.preventDefault(); const f=new FormData(form),body=String(f.get('body')).trim(),official=f.has('official'); if(level<5&&!canModerate&&body.length>30)return alert('LV1–4 每帖最多 30 字。'); const {data:post,error}=await db.from('posts').insert({author_id:user.id,body,category:String(f.get('category')||'综合交流'),official,comment_enabled:official?f.has('comment_enabled'):true,show_timestamp:official?f.has('show_timestamp'):true}).select().single(); if(error)return alert(error.message); for(const file of files){const path=`${user.id}/${crypto.randomUUID()}-${file.name.replace(/[^\w.-]/g,'_')}`;const {error:up}=await db.storage.from('forum-media').upload(path,file,{contentType:file.type});if(up)return alert(up.message);await db.from('post_media').insert({post_id:post.id,path,mime_type:file.type});}form.reset();files=[];load();});
  list.addEventListener('click',async e=>{const id=e.target.dataset.id||e.target.dataset.delete;if(e.target.dataset.react){const {error}=await db.from('post_reactions').insert({post_id:id,user_id:user.id,kind:e.target.dataset.react});if(error&&error.code!=='23505')alert(error.message);load();}if(e.target.dataset.delete&&confirm('确定删除吗？')){await db.from('posts').delete().eq('id',id);load();}if(e.target.dataset.report){const reason=prompt('请输入举报原因（不超过 500 字）：');if(reason){const {error}=await db.from('content_reports').insert({reporter_id:user.id,target_type:'post',target_id:e.target.dataset.report,reason});alert(error?error.message:'举报已提交，管理员将进行处理。');}}});
  document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render();}); search.addEventListener('input',render); document.addEventListener('DOMContentLoaded',init);
})();
