const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const rest=(env,path,init={})=>fetch(`${env.SUPABASE_URL}/rest/v1/${path}`,{...init,headers:{apikey:env.SUPABASE_SERVICE_ROLE_KEY,authorization:`Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`,...init.headers}});
async function currentUser(request,env){const token=request.headers.get('authorization')||'';const r=await fetch(`${env.SUPABASE_URL}/auth/v1/user`,{headers:{authorization:token,apikey:env.SUPABASE_SERVICE_ROLE_KEY}});if(!r.ok)return null;return r.json();}
export async function onRequest({request,env}){try{const user=await currentUser(request,env);if(!user)return json({error:'unauthorized'},401);const roleRes=await rest(env,`profiles?select=id,role&id=eq.${encodeURIComponent(user.id)}`);const [profile]=await roleRes.json();if(!profile||!['admin','superadmin'].includes(profile.role))return json({error:'moderator_only'},403);
if(request.method==='GET'){const r=await rest(env,'wiki_revisions?select=*&status=eq.pending&order=created_at.asc');return new Response(await r.text(),{status:r.status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});}
if(request.method!=='PATCH')return json({error:'method_not_allowed'},405);const body=await request.json();const id=String(body.id||'');const decision=body.decision;if(!id||!['approved','rejected'].includes(decision))return json({error:'invalid_request'},400);const revisionRes=await rest(env,`wiki_revisions?select=*&id=eq.${encodeURIComponent(id)}&status=eq.pending`);const [revision]=await revisionRes.json();if(!revision)return json({error:'revision_not_found'},404);const reviewer_note=String(body.reviewer_note||'').slice(0,500);
if(decision==='approved'){const entry={slug:revision.entry_slug,title:revision.proposed_title,summary:revision.proposed_summary,content:revision.proposed_content,category:revision.proposed_category,updated_at:new Date().toISOString(),updated_by:revision.author_id};const saved=await rest(env,'wiki_entries?on_conflict=slug',{method:'POST',headers:{'content-type':'application/json',prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(entry)});if(!saved.ok)return json({error:'entry_write_failed'},500);}
const updated=await rest(env,`wiki_revisions?id=eq.${encodeURIComponent(id)}&status=eq.pending`,{method:'PATCH',headers:{'content-type':'application/json',prefer:'return=minimal'},body:JSON.stringify({status:decision,reviewer_id:user.id,reviewer_note,reviewed_at:new Date().toISOString()})});return json({ok:updated.ok},updated.ok?200:500);
}catch{return json({error:'server_error'},500)}}
